### ISSUE TITLE
How to achieve visualization?

### ISSUE THREAD

**Issue by shijiunv** [joeycumines/go-behaviortree#8]

**Comment by joeycumines** [comment]
Hi :)

Could you elaborate on what specifically you were after?

This module/package does not provide any visualization capabilities. You can print the general shape of trees using `Node.String`, and it's possible to attach metadata to trees via the context-like value mechanism, but there's nothing analogous to say https://github.com/BehaviorTree/BehaviorTree.CPP + https://github.com/BehaviorTree/Groot.

In the past, I've considered implementing a tool to visualize / debug behavior trees, but I've never encountered a strong enough motivator. Similarly, I've also considered implementing support for the BehaviorTree.CPP project. Again though, that use case runs somewhat counter to my own, so I've never actioned it.

**Comment by joeycumines** [comment]
Closing this due to no response

**Comment by shijiunv** [comment]
Is it possible to output a vector graphic, such as SVG format?

**Comment by joeycumines** [comment]
> Is it possible to output a vector graphic, such as SVG format?

Not as is, no.

In order to make it possible to get a rough idea of the tree structure, the `Node` type does implement `fmt.Stringer`. This is largely for debugging, e.g. verbose but more informative errors, in certain exceptional cases / panics. Attaching additional (more useful) metadata to `Node` values, and implementing a custom `Printer` (e.g. to output SVG), would certainly be feasible, but I'd expect that (depending on use case) it would be more useful to implement the behavior tree structure using a purpose-built data structure, and primarily utilize this library for it's runtime functionality (it's core purpose).

You can get an idea of the available metadata here: https://github.com/joeycumines/go-pabt/blob/fa3e6a36fe3ef8599c433ede14c4f291a2e472aa/graph_test.go#L208

I am curious, what is your use case / what prompted you to ask?

**Comment by shijiunv** [comment]
Used to generate and share business processes
